"""Ego-motion flow module — precomputed affine flow for PoseNet optimization.

The PoseNet scorer measures 6-DOF pose change between consecutive frames.
Frames generated by the renderer lack geometric ego-motion structure because
the MotionPredictor can't infer sub-pixel flow from 5-class integer masks.

This module provides a learnable per-pair affine flow that gives PoseNet
the geometric warp signal it needs. Each pair gets a 6-parameter affine
transform (2×3 matrix) that is learned end-to-end against the scorer loss.

At inference time, the affine parameters are stored in the archive (~3.6KB
at FP4 for 600 pairs) and used to compute dense flow fields on-the-fly.

Architecture:
    flow = affine_to_dense_flow(pair_affine_params[pair_idx], H, W)
    frame_t = warp(frame_t1, flow) + gate * residual

Council decision: Hotz analytical ego-flow + Fridrich Lagrangian optimization.
"""

from __future__ import annotations

import torch
import torch.nn as nn


class LearnableAffineFlow(nn.Module):
    """Per-pair learnable affine flow parameters.

    Stores a (N, 6) parameter table where N is the number of pairs.
    Each row is [a11, a12, tx, a21, a22, ty] defining a 2×3 affine matrix.
    The dense flow field is computed analytically from the affine + pixel coords.

    Initialized to identity (zero flow) so training starts from no-warp.

    Archive cost: N * 6 * 0.5 bytes (FP4) = 600 * 6 * 0.5 = 1800 bytes.
    """

    def __init__(self, n_pairs: int = 600, max_flow_px: float = 20.0):
        super().__init__()
        self.n_pairs = n_pairs
        self.max_flow_px = max_flow_px
        # Initialize with small random translation to break the zero-gradient
        # symmetry at identity warp. Uniform regions have zero spatial gradient,
        # so zero flow = zero gradient for ego_flow params. A small initial
        # displacement ensures the warp samples across pixel boundaries from
        # the very first step, providing gradient signal.
        init = torch.zeros(n_pairs, 6)  # OFF_MANIFOLD_OK: not a PoseNet-input pose — these are AffineFlowField parameters (rotation+translation+shear), an independent 6-DOF affine warp space, not the 6-DOF PoseNet pose vector. Renderer never sees this tensor as `pose=`.
        # Small random translation (channels 2=tx, 5=ty) ~0.5 pixel equivalent
        init[:, 2] = torch.randn(n_pairs) * 0.3  # tx
        init[:, 5] = torch.randn(n_pairs) * 0.3  # ty
        self.affine_deltas = nn.Parameter(init)

    def forward(self, pair_indices: torch.Tensor, H: int, W: int) -> torch.Tensor:
        """Compute dense flow fields from affine parameters.

        Args:
            pair_indices: (B,) long tensor of pair indices into the table
            H, W: spatial dimensions for the output flow field

        Returns:
            (B, 2, H, W) flow in grid_sample normalized coordinates [-1, 1]
        """
        device = self.affine_deltas.device
        B = pair_indices.shape[0]

        # Look up affine deltas for this batch
        deltas = self.affine_deltas[pair_indices]  # (B, 6)

        # Scale deltas through tanh to bound the flow magnitude.
        # align_corners=True convention: 1 px = 2/(W-1) normalized units (not 2/W).
        # Matches MotionPredictor.forward() fix (round 20) and warp_with_flow grid.
        scale_x = self.max_flow_px / (W - 1) * 2
        scale_y = self.max_flow_px / (H - 1) * 2
        deltas = deltas.tanh()
        # Apply per-axis scale: channels 0,1,2 use x-scale, channels 3,4,5 use y-scale
        deltas = torch.cat([deltas[:, :3] * scale_x, deltas[:, 3:] * scale_y], dim=1)

        # Build 2×3 affine matrix: [[1+d0, d1, d2], [d3, 1+d4, d5]]
        # The identity part means zero deltas = zero flow
        a11 = deltas[:, 0]      # scale_x - 1
        a12 = deltas[:, 1]      # shear_xy
        tx = deltas[:, 2]       # translate_x
        a21 = deltas[:, 3]      # shear_yx
        a22 = deltas[:, 4]      # scale_y - 1
        ty = deltas[:, 5]       # translate_y

        # Create normalized pixel grid [-1, 1]
        yy = torch.linspace(-1.0, 1.0, H, device=device)
        xx = torch.linspace(-1.0, 1.0, W, device=device)
        grid_y, grid_x = torch.meshgrid(yy, xx, indexing="ij")  # (H, W) each

        # Expand for batch: (B, H, W)
        gx = grid_x.unsqueeze(0).expand(B, -1, -1)
        gy = grid_y.unsqueeze(0).expand(B, -1, -1)

        # Apply affine: flow = A_delta @ [x, y]^T + t
        # flow_x = a11*x + a12*y + tx
        # flow_y = a21*x + a22*y + ty
        flow_x = (a11.view(B, 1, 1) * gx
                   + a12.view(B, 1, 1) * gy
                   + tx.view(B, 1, 1))
        flow_y = (a21.view(B, 1, 1) * gx
                   + a22.view(B, 1, 1) * gy
                   + ty.view(B, 1, 1))

        # Stack to (B, 2, H, W) — channel 0 = x flow, channel 1 = y flow
        return torch.stack([flow_x, flow_y], dim=1)

    def param_count(self) -> int:
        return self.affine_deltas.numel()

    def archive_bytes_fp4(self) -> int:
        """Estimated archive size at FP4 quantization."""
        return self.affine_deltas.numel() // 2  # 4 bits = 0.5 bytes per param
