"""Tests for Lane Q-FAITHFUL: 1:1 Quantizr PR #55 architecture replica.

Per Round 26 convention, every test asserts a magnitude/sign anchor —
not just "doesn't crash". The architectural invariants are pinned so
silent regressions (e.g. someone adding a motion module back, or
breaking the unconditional/FiLM split) become impossible.
"""
from __future__ import annotations

import pytest
import torch
import torch.nn as nn

from tac.quantizr_faithful_renderer import (
    FiLMFrameHead,
    FiLMSepResBlock,
    Frame2StaticHead,
    FrameHead,
    JointFrameGenerator,
    SepConvGNAct,
    SepResBlock,
    SharedMaskDecoder,
    build_quantizr_faithful_renderer,
    make_coord_grid,
)


# ────────────────────────────────────────────────────────────────────────────
# Architectural invariants (the user's audit said these MUST hold)
# ────────────────────────────────────────────────────────────────────────────


def test_param_count_within_88k_target_band() -> None:
    """Quantizr PR #55: '88k params and 64kb when compressed'.

    Faithful port should land within ±2K of that target. If this drifts
    we either have an extra layer (regression) or are missing one.
    """
    model = build_quantizr_faithful_renderer()
    n_params = sum(p.numel() for p in model.parameters())
    assert 86_000 < n_params < 90_000, (
        f"param count {n_params:,} outside 86K-90K band; Quantizr target "
        f"is 88K. Either an extra module was added or one was dropped."
    )


def test_no_motion_module_present() -> None:
    """The whole point: Quantizr REMOVED the motion module.

    State dict keys must contain ZERO references to motion/warp/flow
    (case-insensitive). The audit
    (.omx/research/quantizr_replica_audit_20260428.md) calls this out as
    delta #1.
    """
    model = build_quantizr_faithful_renderer()
    forbidden_substrings = ("motion", "warp", "flow", "ego_flow", "zoom")
    keys = list(model.state_dict().keys())
    bad = [
        k
        for k in keys
        if any(sub in k.lower() for sub in forbidden_substrings)
    ]
    assert not bad, (
        f"Found motion-related state_dict keys {bad}; Quantizr's "
        f"architecture has NONE. PR body verbatim: 'dropping optical flow'."
    )


def test_forward_shape() -> None:
    """forward(mask2, pose6) -> (frame1, frame2) each (B, 3, H, W)."""
    model = build_quantizr_faithful_renderer()
    B = 2
    mask2 = torch.zeros(B, 384, 512, dtype=torch.long)
    pose6 = torch.zeros(B, 6)
    frame1, frame2 = model(mask2, pose6)
    assert frame1.shape == (B, 3, 384, 512), frame1.shape
    assert frame2.shape == (B, 3, 384, 512), frame2.shape
    # sigmoid * 255 -> outputs must lie within [0, 255] inclusive
    assert frame1.min().item() >= 0.0 and frame1.max().item() <= 255.0
    assert frame2.min().item() >= 0.0 and frame2.max().item() <= 255.0


def test_frame2_unconditional_invariant_to_pose() -> None:
    """frame2 is generated by Frame2StaticHead — NO pose conditioning.

    Varying pose6 must leave frame2 EXACTLY unchanged (not approximately —
    bit-identical, since pose6 doesn't enter the frame2_head graph at all).
    """
    model = build_quantizr_faithful_renderer().eval()
    B = 2
    mask2 = torch.randint(0, 5, (B, 384, 512), dtype=torch.long)

    pose_a = torch.zeros(B, 6)
    pose_b = torch.randn(B, 6) * 5.0  # large perturbation

    with torch.no_grad():
        _, f2_a = model(mask2, pose_a)
        _, f2_b = model(mask2, pose_b)

    diff = (f2_a - f2_b).abs().max().item()
    assert diff == 0.0, (
        f"frame2 is supposed to be UNCONDITIONAL on pose, but max abs "
        f"diff under pose perturbation = {diff}. Bug: pose leaked into "
        f"frame2_head somewhere."
    )


def test_frame1_changes_with_pose() -> None:
    """frame1 is FiLM-conditioned on pose — varying pose6 must MEASURABLY
    change frame1. Magnitude anchor: > 1e-3 (small — even one FiLM gamma
    change should dominate).
    """
    model = build_quantizr_faithful_renderer().eval()
    B = 2
    mask2 = torch.randint(0, 5, (B, 384, 512), dtype=torch.long)

    pose_a = torch.zeros(B, 6)
    pose_b = torch.randn(B, 6) * 5.0

    with torch.no_grad():
        f1_a, _ = model(mask2, pose_a)
        f1_b, _ = model(mask2, pose_b)

    diff = (f1_a - f1_b).abs().max().item()
    assert diff > 1e-3, (
        f"frame1 should respond to pose via FiLM, but max abs diff under "
        f"pose perturbation = {diff:.6e}. Bug: FiLM modulation isn't "
        f"reaching frame1_head (e.g. cond_emb is zero, or the FiLM gamma "
        f"scales were initialized to exactly zero with no bias)."
    )


def test_film_gradient_flows_to_pose_mlp() -> None:
    """Backward pass through frame1 loss must produce non-zero, finite
    gradient on pose_mlp parameters. If grads are None or zero, FiLM is
    effectively disconnected.
    """
    model = build_quantizr_faithful_renderer().train()
    B = 2
    mask2 = torch.randint(0, 5, (B, 384, 512), dtype=torch.long)
    pose6 = torch.randn(B, 6, requires_grad=True)

    f1, _ = model(mask2, pose6)
    loss = f1.mean()
    loss.backward()

    for name, param in model.pose_mlp.named_parameters():
        assert param.grad is not None, f"pose_mlp.{name}.grad is None"
        assert torch.isfinite(param.grad).all(), (
            f"pose_mlp.{name} has non-finite grad"
        )
        nz = (param.grad != 0).any().item()
        assert nz, (
            f"pose_mlp.{name}.grad is identically zero; FiLM disconnected"
        )


def test_5_step_training_loss_decreases() -> None:
    """5-step Adam optimization: loss must STRICTLY decrease across the run.

    Magnitude anchor: final_loss < initial_loss * 0.99 (any fitting at all).
    """
    torch.manual_seed(0)
    model = build_quantizr_faithful_renderer().train()
    B = 2
    mask2 = torch.randint(0, 5, (B, 384, 512), dtype=torch.long)
    pose6 = torch.randn(B, 6)
    target_f1 = torch.randn(B, 3, 384, 512) * 30.0 + 127.5
    target_f2 = torch.randn(B, 3, 384, 512) * 30.0 + 127.5

    optim = torch.optim.Adam(model.parameters(), lr=1e-3)
    losses: list[float] = []
    for step in range(5):
        optim.zero_grad()
        f1, f2 = model(mask2, pose6)
        loss = (f1 - target_f1).abs().mean() + (f2 - target_f2).abs().mean()
        loss.backward()
        optim.step()
        losses.append(loss.item())

    # Each subsequent step should not increase loss; final should be lower.
    assert losses[-1] < losses[0] * 0.99, (
        f"loss did not decrease over 5 steps: {losses}. "
        f"Optimization signal is broken."
    )


def test_film_layer_dimensions_match_quantizr() -> None:
    """pose_mlp: Linear(6, 48) -> SiLU -> Linear(48, 48), exact match
    to Quantizr's `compress.py:204-205`.

    Wrong dims here = silent architectural drift like our prior
    pose_dim=6 (no MLP expansion) bug.
    """
    model = build_quantizr_faithful_renderer()
    seq = model.pose_mlp
    # Should be Sequential(Linear, SiLU, Linear)
    children = list(seq.children())
    assert len(children) == 3, f"expected 3-layer pose_mlp, got {len(children)}"
    l0, act, l1 = children
    assert isinstance(l0, nn.Linear), type(l0)
    assert isinstance(act, nn.SiLU), type(act)
    assert isinstance(l1, nn.Linear), type(l1)
    assert l0.in_features == 6 and l0.out_features == 48, (
        f"pose_mlp[0] expected Linear(6, 48), got "
        f"Linear({l0.in_features}, {l0.out_features})"
    )
    assert l1.in_features == 48 and l1.out_features == 48, (
        f"pose_mlp[2] expected Linear(48, 48), got "
        f"Linear({l1.in_features}, {l1.out_features})"
    )

    # And verify the FiLM projection inside frame1_head consumes 48-dim
    # cond_emb and produces 2*in_ch (= 2*56 = 112) features.
    film = model.frame1_head.block1.film_proj
    assert isinstance(film, nn.Linear)
    assert film.in_features == 48, (
        f"FiLM input dim should be cond_dim=48, got {film.in_features}"
    )
    assert film.out_features == 56 * 2, (
        f"FiLM output dim should be 2*in_ch = 112, got {film.out_features}"
    )


# ────────────────────────────────────────────────────────────────────────────
# Sub-module sanity (the building blocks are individually correct)
# ────────────────────────────────────────────────────────────────────────────


def test_make_coord_grid_layout_matches_quantizr() -> None:
    """make_coord_grid returns (B, 2, H, W) in [-1, 1] (xx, yy)."""
    grid = make_coord_grid(3, 384, 512, "cpu", torch.float32)
    assert grid.shape == (3, 2, 384, 512), grid.shape
    # Should span [-1, 1] in both axes (within the +0.5 cell-center offset)
    xx, yy = grid[0, 0], grid[0, 1]
    assert -1.0 <= xx.min().item() < -0.99
    assert 0.99 < xx.max().item() <= 1.0
    assert -1.0 <= yy.min().item() < -0.99
    assert 0.99 < yy.max().item() <= 1.0


def test_film_block_modulates_proportional_to_cond() -> None:
    """Smoke: FiLMSepResBlock output magnitude scales when cond is large."""
    block = FiLMSepResBlock(ch=8, cond_dim=4, depth_mult=1).eval()
    x = torch.randn(2, 8, 16, 16)
    cond_zero = torch.zeros(2, 4)
    cond_big = torch.randn(2, 4) * 10.0
    with torch.no_grad():
        y_zero = block(x, cond_zero)
        y_big = block(x, cond_big)
    # Both should differ — even cond_zero produces a non-zero film_proj.bias
    # contribution. The point is they aren't IDENTICAL.
    assert (y_zero - y_big).abs().max().item() > 0.0


def test_frame2_static_head_stable_under_input_perturbation() -> None:
    """Sanity that the frame2 head returns finite, in-range output."""
    head = Frame2StaticHead(in_ch=56, hidden=52, depth_mult=1).eval()
    feat = torch.randn(2, 56, 384, 512)
    with torch.no_grad():
        out = head(feat)
    assert out.shape == (2, 3, 384, 512)
    assert torch.isfinite(out).all()
    assert 0.0 <= out.min().item() and out.max().item() <= 255.0


# ────────────────────────────────────────────────────────────────────────────
# Builder smoke
# ────────────────────────────────────────────────────────────────────────────


def test_builder_returns_jointframegenerator() -> None:
    model = build_quantizr_faithful_renderer()
    assert isinstance(model, JointFrameGenerator)
    # default cond_dim=48, pose_dim=6, num_classes=5
    assert model.cond_dim == 48
    assert model.pose_dim == 6
    assert model.num_classes == 5
    # FrameHead alias matches FiLMFrameHead
    assert FrameHead is FiLMFrameHead


# ────────────────────────────────────────────────────────────────────────────
# QFAI export/load roundtrip + inflate-shim integration
# ────────────────────────────────────────────────────────────────────────────


def test_quantizr_faithful_export_roundtrip(tmp_path) -> None:
    """save_qfai -> load_qfai produces a model with bit-identical outputs."""
    from tac.quantizr_faithful_export import load_qfai, save_qfai

    torch.manual_seed(7)
    model_a = build_quantizr_faithful_renderer().eval()
    out_path = tmp_path / "model.qfai.bin"
    n_bytes = save_qfai(model_a, out_path)
    assert n_bytes > 0
    # Magic bytes correct
    assert out_path.read_bytes()[:4] == b"QFAI"

    model_b = load_qfai(out_path, device="cpu").eval()

    # Same arch fields
    assert model_b.num_classes == model_a.num_classes
    assert model_b.pose_dim == model_a.pose_dim
    assert model_b.cond_dim == model_a.cond_dim

    # Bit-identical outputs on a fixed input
    mask2 = torch.randint(0, 5, (2, 384, 512), dtype=torch.long)
    pose6 = torch.randn(2, 6)
    with torch.no_grad():
        f1_a, f2_a = model_a(mask2, pose6)
        f1_b, f2_b = model_b(mask2, pose6)
    assert torch.equal(f1_a, f1_b), (
        f"frame1 differs after roundtrip; max |diff| = "
        f"{(f1_a - f1_b).abs().max().item()}"
    )
    assert torch.equal(f2_a, f2_b), (
        f"frame2 differs after roundtrip; max |diff| = "
        f"{(f2_a - f2_b).abs().max().item()}"
    )


def test_inflate_shim_returns_hwc_pair(tmp_path) -> None:
    """The QFAI inflate dispatch wraps the model in a shim that returns the
    AsymmetricPairGenerator-style (B, 2, H, W, 3) HWC pair so the rest of
    inflate_renderer.py routes through the pair iteration code path
    unmodified.
    """
    from tac.quantizr_faithful_export import save_qfai

    torch.manual_seed(11)
    model = build_quantizr_faithful_renderer().eval()
    out_path = tmp_path / "model.qfai.bin"
    save_qfai(model, out_path)

    # Import the inflate-side loader (it lives in the submission, not tac).
    import importlib.util
    inflate_path = (
        Path(__file__).resolve().parents[3]
        / "submissions" / "robust_current" / "inflate_renderer.py"
    )
    spec = importlib.util.spec_from_file_location("_inflate_under_test", inflate_path)
    inflate_mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(inflate_mod)

    wrapped = inflate_mod._load_renderer(str(out_path), device="cpu")

    # Quack-test: shim flag set, _is_asymmetric_model returns True
    assert getattr(wrapped, "q_faithful", False)
    assert inflate_mod._is_asymmetric_model(wrapped)
    assert wrapped.pose_dim == 6

    # Forward through the asym-style API: (mask_t, mask_t1, pose=...) ->
    # (B, 2, H, W, 3) HWC float in [0, 255].
    B = 2
    mask_t = torch.zeros(B, 384, 512, dtype=torch.long)  # discarded
    mask_t1 = torch.randint(0, 5, (B, 384, 512), dtype=torch.long)
    pose = torch.randn(B, 6)
    with torch.no_grad():
        pair = wrapped(mask_t, mask_t1, pose=pose)
    assert pair.shape == (B, 2, 384, 512, 3), pair.shape
    assert torch.isfinite(pair).all()
    assert 0.0 <= pair.min().item() and pair.max().item() <= 255.0


def test_inflate_shim_drops_mask_t_invariant(tmp_path) -> None:
    """Strict mask_t-discard invariant via the inflate shim path.

    The inflate shim must EXPLICITLY discard mask_t. Varying mask_t
    must not change the output (Quantizr's design: only mask_t1 enters
    the trunk).
    """
    from tac.quantizr_faithful_export import save_qfai

    torch.manual_seed(13)
    model = build_quantizr_faithful_renderer().eval()
    out_path = tmp_path / "model.qfai.bin"
    save_qfai(model, out_path)

    import importlib.util
    inflate_path = (
        Path(__file__).resolve().parents[3]
        / "submissions" / "robust_current" / "inflate_renderer.py"
    )
    spec = importlib.util.spec_from_file_location("_inflate_under_test_mask_t", inflate_path)
    inflate_mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(inflate_mod)

    wrapped = inflate_mod._load_renderer(str(out_path), device="cpu")

    B = 2
    mask_t1 = torch.randint(0, 5, (B, 384, 512), dtype=torch.long)
    pose = torch.zeros(B, 6)
    mask_t_a = torch.zeros(B, 384, 512, dtype=torch.long)
    mask_t_b = torch.randint(0, 5, (B, 384, 512), dtype=torch.long)
    with torch.no_grad():
        pair_a = wrapped(mask_t_a, mask_t1, pose=pose)
        pair_b = wrapped(mask_t_b, mask_t1, pose=pose)
    assert torch.equal(pair_a, pair_b), (
        "Inflate shim is supposed to discard mask_t, but output changes "
        "when mask_t is varied — bug in the shim."
    )


def test_quantizr_qzs3_codec_roundtrip_loads(tmp_path) -> None:
    """QZS3 is the compact PR #67-style packer for JointFrameGenerator."""
    from tac.quantizr_faithful_export import save_qfai
    from tac.quantizr_qzs3_codec import encode_qzs3_state_dict, load_qzs3

    torch.manual_seed(17)
    model_a = build_quantizr_faithful_renderer().eval()
    qfai_path = tmp_path / "model.qfai.bin"
    save_qfai(model_a, qfai_path)

    payload = encode_qzs3_state_dict(model_a)
    assert payload[:4] == b"QZS3"
    assert len(payload) < qfai_path.stat().st_size

    model_b = load_qzs3(payload, device="cpu").eval()
    assert isinstance(model_b, JointFrameGenerator)
    assert list(model_b.state_dict()) == list(model_a.state_dict())
    for tensor in model_b.state_dict().values():
        if torch.is_floating_point(tensor):
            assert torch.isfinite(tensor).all()

    mask2 = torch.randint(0, 5, (1, 384, 512), dtype=torch.long)
    pose6 = torch.randn(1, 6)
    with torch.no_grad():
        f1, f2 = model_b(mask2, pose6)
    assert f1.shape == (1, 3, 384, 512)
    assert f2.shape == (1, 3, 384, 512)
    assert torch.isfinite(f1).all()
    assert torch.isfinite(f2).all()


def test_inflate_shim_loads_qzs3(tmp_path) -> None:
    """The contest inflate loader recognizes QZS3 renderer.bin payloads."""
    from tac.quantizr_qzs3_codec import encode_qzs3_state_dict

    torch.manual_seed(19)
    model = build_quantizr_faithful_renderer().eval()
    out_path = tmp_path / "renderer.bin"
    out_path.write_bytes(encode_qzs3_state_dict(model))

    import importlib.util
    inflate_path = (
        Path(__file__).resolve().parents[3]
        / "submissions" / "robust_current" / "inflate_renderer.py"
    )
    spec = importlib.util.spec_from_file_location("_inflate_under_test_qzs3", inflate_path)
    inflate_mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(inflate_mod)

    wrapped = inflate_mod._load_renderer(str(out_path), device="cpu")

    assert getattr(wrapped, "q_faithful", False)
    assert inflate_mod._is_asymmetric_model(wrapped)
    assert wrapped.pose_dim == 6

    mask_t = torch.zeros(1, 384, 512, dtype=torch.long)
    mask_t1 = torch.randint(0, 5, (1, 384, 512), dtype=torch.long)
    pose = torch.randn(1, 6)
    with torch.no_grad():
        pair = wrapped(mask_t, mask_t1, pose=pose)
    assert pair.shape == (1, 2, 384, 512, 3), pair.shape
    assert torch.isfinite(pair).all()


# Keep imports needed for the inflate-shim tests at module level so they
# error early if the path resolves wrong.
from pathlib import Path  # noqa: E402  (intentional bottom import)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
